# Generated by Django 4.2.5 on 2023-09-27 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_first_name', models.CharField(max_length=50)),
                ('reservation_last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_datetime', models.DateTimeField()),
                ('number_of_guests', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReservationsApp.user')),
            ],
        ),
    ]
