# Generated by Django 4.2.5 on 2023-09-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservations',
            new_name='Reservation',
        ),
    ]
