# Generated by Django 4.2.5 on 2023-09-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationsApp', '0002_rename_reservations_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_first_name',
            field=models.CharField(default='555-55-5555', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_last_name',
            field=models.CharField(default='valencerina', max_length=50),
            preserve_default=False,
        ),
    ]
